name: run-python-validation-script

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

     - name: execute python script
       run: python tests/validate_mappings_file.py zoomage_report.CURATED.tsv
